name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      HELMFILE_PATH: ./helmfile.yaml
      # Add other environment variables as needed 
      GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
      REPO_NAME: ${REPO_NAME}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Helm and Helmfile
        uses: azure/setup-helm@v1
        with:
          version: latest

      - name: Add Helm Repository
        run: |
          helm repo add $REPO_NAME https://raw.githubusercontent.com/$USERNAME/$REPO_NAME/main/helmcharts

      - name: Index Helm Charts
        run: |
          helm repo index $CHARTS_PATH 
      
      - name: Deploy with Helmfile
        run: |
          helmfile --file $HELMFILE_PATH apply

      - name: Deploy with Helmfile
        run: |
          helmfile --file $HELMFILE_PATH apply

        
