name: Setup Environment Variables

on:
  push:
    branches:
      - main

jobs:
  setup-env-vars:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 14

    - name: Install dependencies
      run: npm install

    - name: Run script to set up environment variables
      run: node setup-env-vars.js
      env:
        REPO_CONFIG: ${{ toJson(github.event_name, github.event.client_payload) }}
