name: Setup Environment Variables

on:
  push:
    branches:
      - main

jobs:
  setup-env-vars:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up environment variables
      run: |
        echo "REPO_NAME=owldq-dev" >> $GITHUB_ENV
        echo "DESCRIPTION=Your repository description" >> $GITHUB_ENV
        echo "PRIVATE=false" >> $GITHUB_ENV
        echo "INITIALIZE_README=true" >> $GITHUB_ENV
        echo "DELETE_REPO=false" >> $GITHUB_ENV
        echo "USERNAME=vamshionrails" >> $GITHUB_ENV
        echo "HELMFILE_PATH=./helmfile.yaml" >> $GITHUB_ENV
        echo "CHARTS_PATH=./helmcharts" >> $GITHUB_ENV
        echo "REPO_URL=https://raw.githubusercontent.com/\$USERNAME/\$REPO_NAME/main/helmcharts" >> $GITHUB_ENV
