name: Load JSON and Set Variables

on:
  push:
    branches:
      - main

jobs:
  load-json-and-set-vars:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Load JSON and set variables
      id: set-env-vars
      run: |
        JSON_CONTENT=$(cat owldq-dev.json)
        echo "JSON_CONTENT=$JSON_CONTENT" >> $GITHUB_ENV

        # Set individual variables
        echo "REPO_NAME=$(echo "$JSON_CONTENT" | jq -r '.REPO_NAME')" >> $GITHUB_ENV
        echo "DESCRIPTION=$(echo "$JSON_CONTENT" | jq -r '.DESCRIPTION')" >> $GITHUB_ENV
        echo "PRIVATE=$(echo "$JSON_CONTENT" | jq -r '.PRIVATE')" >> $GITHUB_ENV

        # Set nested variables
        echo "TEST_NAME=$(echo "$JSON_CONTENT" | jq -r '.TEST.TEST_NAME')" >> $GITHUB_ENV

        # Set variables from TEST_ARRAY
        TEST_ARRAY_LENGTH=$(echo "$JSON_CONTENT" | jq -r '.TEST_ARRAY | length')
        for ((i=0; i<$TEST_ARRAY_LENGTH; i++)); do
          TEST_ARRAY_NAME=$(echo "$JSON_CONTENT" | jq -r ".TEST_ARRAY[$i].TEST_ARRAY_NAME")
          echo "TEST_ARRAY_NAME_$i=$TEST_ARRAY_NAME" >> $GITHUB_ENV
        done

    - name: Display environment variables
      run: env
