name: Setup Environment Variables

on:
  push:
    branches:
      - main

jobs:
  setup-env-vars:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install jq
      run: sudo apt-get update && sudo apt-get install -y jq

    - name: Set up environment variables
      run: |
        CONFIG_JSON=$(cat owldq-dev.json)
        for key in $(echo $CONFIG_JSON | jq -r 'keys_unsorted[]'); do
          value=$(echo $CONFIG_JSON | jq -r ".$key")
          echo "$key=$value" >> $GITHUB_ENV
        done 
        
    - name: values for varaiables
      run: |
        echo "DESCRIPTION=$DESCRIPTION"
        
    - name: Display environment variables
      run: env
