name: Setup Environment Variables

on:
  push:
    branches:
      - main

jobs:
  setup-env-vars:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up environment variables
      run: |
        REPO_CONFIG=$(cat owldq-dev.json)
        echo "REPO_CONFIG=$REPO_CONFIG" >> $GITHUB_ENV
