name: Load JSON and Set Environment Variables

on:
  push:
    branches:
      - main

jobs:
  load-json-and-set-vars:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install jq
      run: sudo apt-get update && sudo apt-get install -y jq

    - name: Load JSON and set environment variables
      id: set-env-vars
      run: |
        JSON_CONTENT=$(cat path/to/your/config.json)
        echo "JSON_CONTENT=$JSON_CONTENT" >> $GITHUB_ENV

        # Set variables for all keys, including nested ones
        set_env_vars_recursive() {
          local json="$1"
          local prefix="$2"

          for key in $(echo $json | jq -r 'keys_unsorted[]'); do
            value=$(echo $json | jq -r ".$key")

            # Handle nested objects
            if [ "$(echo $value | jq -e 'type')" == "object" ]; then
              set_env_vars_recursive "$value" "${prefix}${key}_"
            else
              echo "${prefix}${key}=$value" >> $GITHUB_ENV
            fi
          done
        }

        # Call the function for the top-level JSON
        set_env_vars_recursive "$JSON_CONTENT" ""

    - name: Display environment variables
      run: env
