name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  read_json_and_set_env:
    runs-on: ubuntu-latest

    env:
      HELMFILE_PATH: ./helmfile.yaml
      # Add other environment variables as needed 
      GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
      REPO_NAME: ${REPO_NAME}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Helm and Helmfile
        uses: azure/setup-helm@v1
        with:
          version: latest


      - name: Parse JSON to Env Variables
        run: |
          # Install jq (if not already installed)
          sudo apt-get update
          sudo apt-get install jq

          # Read JSON file
          JSON_CONTENT=$(cat ./owldq-dev.json)

          # Iterate over JSON keys and set them as environment variables
          echo "$JSON_CONTENT" | jq -r 'to_entries | .[] | "export \(.key)=\(.value)"' | while read -r line; do
            eval "$line"
          done
      
      - name: Display Environment Variables
        run: |
          echo "REPO_NAME: $REPO_NAME"
          echo "DESCRIPTION: $DESCRIPTION"
          echo "PRIVATE: $PRIVATE"
          echo "INITIALIZE_README: $INITIALIZE_README"
          echo "DELETE_REPO: $DELETE_REPO"
          echo "USERNAME: $USERNAME"
          echo "HELMFILE_PATH: $HELMFILE_PATH"
          echo "CHARTS_PATH: $CHARTS_PATH"
          echo "REPO_URL: $REPO_URL"

      - name: Add Helm Repository
        run: |
          helm repo add $REPO_NAME https://raw.githubusercontent.com/$USERNAME/$REPO_NAME/main/helmcharts

      - name: Index Helm Charts
        run: |
          helm repo index $CHARTS_PATH 
      
      - name: Deploy with Helmfile
        run: |
          helmfile --file $HELMFILE_PATH apply

      - name: Deploy with Helmfile
        run: |
          helmfile --file $HELMFILE_PATH apply

        
